version: '3.8'
services:
  web:
    image: lucadruda/nextjs-starter-project
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
    command: next dev