name: Build and Push Docker Image
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: lucadruda475/nextjs-starter-project:latest
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}